export enum BlockTypes {
    UNSTYLED = 'unstyled',
    PARAGRAPH = 'unstyled',
    OL = 'ordered-list-item',
    UL = 'unordered-list-item',
    H1 = 'header-one',
    H2 = 'header-two',
    H3 = 'header-three',
    H4 = 'header-four',
    H5 = 'header-five',
    H6 = 'header-six',
    BLOCKQUOTE = 'blockquote',
    ATOMIC = 'atomic',
    CONCLUSION = 'conclusion',
    YOUTUBE = 'youtube',
    IMAGE = 'image',
    HR = 'hr',
}
