export enum TagTypes {
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  BLOCKQUOTE = 'blockquote',
  PARAGRAPH = 'p',
  LINK = 'a',
  LI = 'li',
  UL = 'ul',
  OL = 'ol',
  BOLD = 'strong',
  ITALIC = 'em',
  STRIKETHROUGH = 'del',
}
